# Generated by Django 5.1.3 on 2024-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_workexperience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
    ]
