# Generated by Django 5.1.3 on 2024-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_workexperience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default='No Subject', max_length=255),
        ),
    ]
